version: "3.9"

services:
  db:
    image: postgres:15
    container_name: devsoulify-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devsoulify
    ports:
      - "5432:5432"
    volumes:
      - devsoulify_data:/var/lib/postgresql/data

volumes:
  devsoulify_data:
